// Generated by kea-typegen on Sun, 05 Mar 2023 18:21:13 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { Step } from './eventFunnelLogic'
import type { EventStats } from '../lib/api'

export interface eventDetailsLogicType extends Logic {
  actionCreators: {
    setResults: (
      i: number,
      step: Step
    ) => {
      type: 'set results (src.components.EventDetails)'
      payload: {
        i: number
        step: Step
      }
    }
    setStats: (stats: EventStats[]) => {
      type: 'set stats (src.components.EventDetails)'
      payload: {
        stats: EventStats[]
      }
    }
    setSelectedEvent: (event: string) => {
      type: 'set selected event (src.components.EventDetails)'
      payload: {
        event: string
      }
    }
    loadStats: () => {
      type: 'load stats (src.components.EventDetails)'
      payload: {}
    }
    setStatsSuccess: (
      stats: EventStats[],
      payload?: {
        stats: EventStats[]
      }
    ) => {
      type: 'set stats success (src.components.EventDetails)'
      payload: {
        stats: EventStats[]
        payload?: {
          stats: EventStats[]
        }
      }
    }
    setStatsFailure: (
      error: string,
      errorObject?: any
    ) => {
      type: 'set stats failure (src.components.EventDetails)'
      payload: {
        error: string
        errorObject?: any
      }
    }
  }
  actionKeys: {
    'set results (src.components.EventDetails)': 'setResults'
    'set stats (src.components.EventDetails)': 'setStats'
    'set selected event (src.components.EventDetails)': 'setSelectedEvent'
    'load stats (src.components.EventDetails)': 'loadStats'
    'set stats success (src.components.EventDetails)': 'setStatsSuccess'
    'set stats failure (src.components.EventDetails)': 'setStatsFailure'
  }
  actionTypes: {
    setResults: 'set results (src.components.EventDetails)'
    setStats: 'set stats (src.components.EventDetails)'
    setSelectedEvent: 'set selected event (src.components.EventDetails)'
    loadStats: 'load stats (src.components.EventDetails)'
    setStatsSuccess: 'set stats success (src.components.EventDetails)'
    setStatsFailure: 'set stats failure (src.components.EventDetails)'
  }
  actions: {
    setResults: (i: number, step: Step) => void
    setStats: (stats: EventStats[]) => void
    setSelectedEvent: (event: string) => void
    loadStats: () => void
    setStatsSuccess: (
      stats: EventStats[],
      payload?: {
        stats: EventStats[]
      }
    ) => void
    setStatsFailure: (error: string, errorObject?: any) => void
  }
  asyncActions: {
    setResults: (i: number, step: Step) => Promise<any>
    setStats: (stats: EventStats[]) => Promise<any>
    setSelectedEvent: (event: string) => Promise<any>
    loadStats: () => Promise<any>
    setStatsSuccess: (
      stats: EventStats[],
      payload?: {
        stats: EventStats[]
      }
    ) => Promise<any>
    setStatsFailure: (error: string, errorObject?: any) => Promise<any>
  }
  defaults: {
    stats: EventStats[]
    statsLoading: boolean
    selectedEvent: string
  }
  events: {
    afterMount: () => void
  }
  key: undefined
  listeners: {
    loadStats: ((
      action: {
        type: 'load stats (src.components.EventDetails)'
        payload: {}
      },
      previousState: any
    ) => void | Promise<void>)[]
    'set results (src.scenes.eventFunnelLogic)': ((
      action: {
        type: 'set results (src.scenes.eventFunnelLogic)'
        payload: {
          i: number
          step: Step
        }
      },
      previousState: any
    ) => void | Promise<void>)[]
  }
  path: ['src', 'components', 'EventDetails']
  pathString: 'src.components.EventDetails'
  props: Record<string, unknown>
  reducer: (
    state: any,
    action: any,
    fullState: any
  ) => {
    stats: EventStats[]
    statsLoading: boolean
    selectedEvent: string
  }
  reducers: {
    stats: (state: EventStats[], action: any, fullState: any) => EventStats[]
    statsLoading: (state: boolean, action: any, fullState: any) => boolean
    selectedEvent: (state: string, action: any, fullState: any) => string
  }
  selector: (state: any) => {
    stats: EventStats[]
    statsLoading: boolean
    selectedEvent: string
  }
  selectors: {
    stats: (state: any, props?: any) => EventStats[]
    statsLoading: (state: any, props?: any) => boolean
    selectedEvent: (state: any, props?: any) => string
  }
  sharedListeners: {}
  values: {
    stats: EventStats[]
    statsLoading: boolean
    selectedEvent: string
  }
  _isKea: true
  _isKeaWithKey: false
  __keaTypeGenInternalReducerActions: {
    'set results (src.scenes.eventFunnelLogic)': (
      i: number,
      step: Step
    ) => {
      type: 'set results (src.scenes.eventFunnelLogic)'
      payload: {
        i: number
        step: Step
      }
    }
  }
}
